# Generated by Django 5.2.5 on 2025-08-08 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='招待コード')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.managementoffice', verbose_name='管理所')),
            ],
        ),
    ]
