# Generated by Django 5.2.5 on 2025-08-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_customuser_email_invitationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='reservations.facility', verbose_name='施設')),
            ],
        ),
    ]
