# Generated by Django 5.2.4 on 2025-08-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_facilitytimeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitytimeslot',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.facility', verbose_name='施設'),
        ),
        migrations.CreateModel(
            name='FacilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='施設識別名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.facility', verbose_name='施設タイプ')),
            ],
        ),
    ]
