# Generated by Django 5.2.5 on 2025-08-12 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_facilitytimeslot_facility_facilityitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='facility',
        ),
        migrations.AddField(
            model_name='reservation',
            name='facilityItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.facilityitem', verbose_name='施設'),
        ),
    ]
